const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const sharp = require('sharp');
const { z } = require('zod');
const db = require('../db/database');
const env = require('../config/env');
const { FIELDS } = require('./declaration-extraction.service');

const PROMPT_VERSION = 'VISION-1.3';
const candidateSchema = z.object({ field: z.enum(FIELDS), value: z.string().nullable(), confidence: z.number().min(0).max(1), state: z.enum(['DETECTED', 'LOW_CONFIDENCE', 'NOT_DETECTED']), sourceSide: z.enum(['FRONT', 'BACK', 'ADDITIONAL']).nullable(), visualEvidenceDescription: z.string().nullable() });
const outputSchema = z.object({ declarations: z.array(candidateSchema) });
const structuredResponseFormat = { type: 'json_schema', json_schema: { name: 'legalmetrix_visual_declarations', strict: true, schema: { type: 'object', additionalProperties: false, required: ['declarations'], properties: { declarations: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['field', 'value', 'confidence', 'state', 'sourceSide', 'visualEvidenceDescription'], properties: { field: { type: 'string', enum: FIELDS }, value: { type: ['string', 'null'] }, confidence: { type: 'number', minimum: 0, maximum: 1 }, state: { type: 'string', enum: ['DETECTED', 'LOW_CONFIDENCE', 'NOT_DETECTED'] }, sourceSide: { enum: ['FRONT', 'BACK', 'ADDITIONAL', null] }, visualEvidenceDescription: { type: ['string', 'null'] } } } } } } } };
const rootDir = path.resolve(__dirname, '../..');
const key = value => String(value || '').toLowerCase().replace(/[^a-z0-9]/g, '');
function parseOutput(content) { const raw = String(content || '').trim(); const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]; const marker = raw.search(/\{\s*"declarations"\s*:/); const cleaned = (fenced || (marker >= 0 ? raw.slice(marker, raw.lastIndexOf('}') + 1) : raw)).trim(); return outputSchema.parse(JSON.parse(cleaned || '{}')); }
function validCandidate(candidate) {
  if (!candidate.value) return candidate.sourceSide === null && candidate.visualEvidenceDescription === null;
  if (!candidate.sourceSide || !candidate.visualEvidenceDescription || candidate.visualEvidenceDescription.trim().length < 5) return false;
  const description = candidate.visualEvidenceDescription.toLowerCase();
  if (candidate.field === 'manufacturer' && !/(manufactured\s+by|mfd\.?\s+by)/i.test(description)) return false;
  if (candidate.field === 'manufacturer_address' && !/(manufacturer|manufactured\s+by|mfd\.?\s+by)/i.test(description)) return false;
  if (candidate.field === 'packer' && !/(packed\s+by|packer)/i.test(description)) return false;
  if (candidate.field === 'importer' && !/(imported\s+by|importer)/i.test(description)) return false;
  if (candidate.field === 'country_of_origin' && (!/(country\s+of\s+origin|made\s+in|manufactured\s+in)/i.test(description) || /address/i.test(description))) return false;
  if (candidate.field === 'consumer_care_phone' && candidate.value.replace(/\D/g, '').length < 8) return false;
  if (candidate.field === 'consumer_care_email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(candidate.value)) return false;
  if (['mrp', 'unit_sale_price'].includes(candidate.field) && (!/\d/.test(candidate.value) || !/(?:₹|rs\.?|inr)/i.test(candidate.value))) return false;
  if (candidate.field === 'net_quantity' && !/^\s*\d+(?:\.\d+)?\s*(?:kg|g|gm|grams?|ml|l|lit(?:re|er)?s?)\s*$/i.test(candidate.value)) return false;
  return key(candidate.value).length >= 2;
}
function normalize(candidate) { if (!candidate.value) return { ...candidate, value: null, confidence: 0, state: 'NOT_DETECTED', sourceSide: null, visualEvidenceDescription: null }; let value = candidate.value.trim(); let confidence = candidate.confidence; const description = candidate.visualEvidenceDescription.trim(); if (candidate.field === 'mrp') { const amount = value.match(/(?:₹|rs\.?|inr)\s*(\d+(?:\.\d{1,2})?)/i); if (amount) value = `₹${amount[1]}`; } if (candidate.state === 'LOW_CONFIDENCE' || /(?:likely|possibly|uncertain|appears to|may be)/i.test(description)) confidence = Math.min(confidence, .6); return { ...candidate, value, confidence, state: confidence < .65 || candidate.state === 'NOT_DETECTED' ? 'LOW_CONFIDENCE' : candidate.state, visualEvidenceDescription: description }; }
function ocrLocationHint(text = '') { const pattern = /(?:manufact|mfd|packed|packer|import|marketed|pharma|equipment|address|plot|sector|road|india|net|quantity|content|mrp|price|consumer|care|email|expiry|best|batch|unit|sale)/i; return text.split(/\r?\n/).map(line => line.trim()).filter(line => line && pattern.test(line)).slice(0, 18).join('\n').slice(0, 900); }
function cacheKey(images) { const hash = crypto.createHash('sha256').update(`${PROMPT_VERSION}|${env.visionExtractionModel}`); for (const image of [...images].sort((a, b) => `${a.image_type}:${a.id}`.localeCompare(`${b.image_type}:${b.id}`))) { hash.update(`${image.image_type}:${image.id}:`); hash.update(fs.readFileSync(path.resolve(rootDir, image.storage_path))); } return hash.digest('hex'); }
function legacyCacheKey(images, version) { const hash = crypto.createHash('sha256').update(`${version}|${env.visionExtractionModel}`); for (const image of [...images].sort((a, b) => `${a.image_type}:${a.id}`.localeCompare(`${b.image_type}:${b.id}`))) { hash.update(`${image.image_type}:${image.id}:`); hash.update(fs.readFileSync(path.resolve(rootDir, image.storage_path))); } return hash.digest('hex'); }
async function compressedImage(image) { const originalPath = path.resolve(rootDir, image.storage_path); const originalBytes = fs.statSync(originalPath).size; const buffer = await sharp(originalPath).rotate().resize({ width: 1400, height: 1400, fit: 'inside', withoutEnlargement: true }).flatten({ background: '#ffffff' }).jpeg({ quality: 78 }).toBuffer(); return { side: image.image_type, buffer, originalBytes, ocrHint: ocrLocationHint(image.ocr_hint || image.normalized_ocr_text || image.ocr_text) }; }
async function extractVisually({ inspectionId, images }) {
  const fingerprint = cacheKey(images); const cached = db.prepare('SELECT vision_cache_key, vision_extraction_json, vision_diagnostics_json FROM inspections WHERE id = ?').get(inspectionId);
  if (cached?.vision_cache_key === fingerprint && cached.vision_extraction_json) { try { const candidates = z.array(candidateSchema).parse(JSON.parse(cached.vision_extraction_json)).map(normalize).filter(validCandidate); const previous = JSON.parse(cached.vision_diagnostics_json || '{}'); return { candidates, diagnostics: { ...previous, cacheHit: true, invoked: false, fallbackUsed: false, output: candidates } }; } catch { /* Invalid old cache is ignored and replaced. */ } }
  if (cached?.vision_extraction_json) { try { const previous = JSON.parse(cached.vision_diagnostics_json || '{}'); const compatibleVersion = ['VISION-1.1'].includes(previous.promptVersion); if (compatibleVersion && previous.success && previous.model === env.visionExtractionModel && cached.vision_cache_key === legacyCacheKey(images, previous.promptVersion)) { const candidates = z.array(candidateSchema).parse(JSON.parse(cached.vision_extraction_json)).map(normalize).filter(validCandidate); return { candidates, diagnostics: { ...previous, cacheHit: true, cacheRevalidated: true, activeValidationVersion: PROMPT_VERSION, invoked: false, fallbackUsed: false, output: candidates } }; } } catch { /* Incompatible old cache is ignored. */ } }
  const diagnostics = { invoked: false, mode: 'VISION', provider: env.aiExtractionBaseUrl.includes('openrouter.ai') ? 'OpenRouter' : 'OpenAI-compatible', model: env.visionExtractionModel, promptVersion: PROMPT_VERSION, imageCount: images.length, originalImageBytes: 0, compressedImageBytes: 0, cacheHit: false, success: false, fallbackUsed: true, durationMs: 0, usage: null, error: null, output: null };
  if (!env.aiExtractionApiKey || !env.visionExtractionModel) { diagnostics.error = 'Vision extraction is not configured.'; return { candidates: [], diagnostics }; }
  const started = Date.now(); let responseContent = '';
  try {
    const prepared = await Promise.all(images.map(compressedImage)); diagnostics.originalImageBytes = prepared.reduce((sum, item) => sum + item.originalBytes, 0); diagnostics.compressedImageBytes = prepared.reduce((sum, item) => sum + item.buffer.length, 0);
    const prompt = `Inspect the supplied package-label images and extract declarations from visible pixels only. Do not use legal rules and do not decide compliance. Return one object for every allowed field: ${FIELDS.join(', ')}. Every non-null value must be visibly readable in its source image. Never infer, autocomplete, repair, or fabricate obscured characters, prices, dates, contacts, names, or addresses. Use LOW_CONFIDENCE when characters are ambiguous and NOT_DETECTED when unreadable. visualEvidenceDescription must briefly identify the visible region, for example "price printed in bottom label region", without making a legal conclusion. Inspect the complete manufactured-by block. Assign manufacturer only from text explicitly linked to manufactured by or Mfd. by, never marketed by. Assign packer only from packed by/packer text, and importer only from imported by/importer text. manufacturer_address must belong to the explicit manufacturer. country_of_origin requires an explicit country-of-origin, made-in, or manufactured-in declaration, not merely an address. For mrp return only the total retail price; put price-per-unit text only in unit_sale_price. When two unlabeled dates are merely adjacent, use LOW_CONFIDENCE rather than deciding their meaning.`;
    const content = [{ type: 'text', text: prompt }]; for (const item of prepared) { content.push({ type: 'text', text: `SOURCE SIDE: ${item.side}${item.ocrHint ? `\nNOISY OCR LOCATION HINT (use only to locate text; verify every value in the image pixels):\n${item.ocrHint}` : ''}` }); content.push({ type: 'image_url', image_url: { url: `data:image/jpeg;base64,${item.buffer.toString('base64')}` } }); }
    diagnostics.invoked = true;
    const response = await fetch(env.aiExtractionBaseUrl, { method: 'POST', signal: AbortSignal.timeout(60000), headers: { Authorization: `Bearer ${env.aiExtractionApiKey}`, 'Content-Type': 'application/json', ...(env.aiExtractionBaseUrl.includes('openrouter.ai') ? { 'HTTP-Referer': 'http://localhost:5173', 'X-Title': 'LegalMetrix' } : {}) }, body: JSON.stringify({ model: env.visionExtractionModel, temperature: 0, max_tokens: 2500, reasoning: { enabled: false }, response_format: structuredResponseFormat, messages: [{ role: 'system', content: 'Return strict JSON only. Extract visible declarations; never assess compliance.' }, { role: 'user', content }] }) });
    const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || `Vision provider returned HTTP ${response.status}`); diagnostics.usage = payload.usage || null; responseContent = payload.choices?.[0]?.message?.content || ''; const parsed = parseOutput(responseContent); const candidates = parsed.declarations.map(normalize).filter(validCandidate);
    diagnostics.success = true; diagnostics.fallbackUsed = false; diagnostics.output = candidates; diagnostics.durationMs = Date.now() - started;
    db.prepare('UPDATE inspections SET vision_cache_key = ?, vision_extraction_json = ?, vision_diagnostics_json = ?, vision_completed_at = CURRENT_TIMESTAMP WHERE id = ?').run(fingerprint, JSON.stringify(candidates), JSON.stringify(diagnostics), inspectionId);
    return { candidates, diagnostics };
  } catch (error) { diagnostics.error = error.message; diagnostics.durationMs = Date.now() - started; if (responseContent) diagnostics.rawOutputPreview = responseContent.slice(0, 1200); return { candidates: [], diagnostics }; }
}
module.exports = { extractVisually, candidateSchema, PROMPT_VERSION, normalizeVisionCandidate: normalize, validVisionCandidate: validCandidate };
