import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { request } from '../lib/api';
import { useAuth } from '../lib/auth';
import { StatusBadge } from '../components/StatusBadge';
import { EmptyState } from '../components/EmptyState';

const initial = { productName: '', genericName: '', brandName: '', location: '', notes: '' };
export function InspectionsPage() {
  const { token } = useAuth(); const navigate = useNavigate(); const [items, setItems] = useState([]); const [filters, setFilters] = useState({ search: '', state: '', from: '', to: '' }); const [form, setForm] = useState(initial); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = () => { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); return request(`/inspections?${query}`, { token }).then(x => setItems(x.inspections)).catch(e => setError(e.message)); };
  useEffect(() => { load(); }, [token, filters.search, filters.state, filters.from, filters.to]);
  async function create(event) { event.preventDefault(); setSaving(true); setError(''); try { const { inspection } = await request('/inspections', { token, method: 'POST', body: form }); navigate(`/inspections/${inspection.id}`); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  return <><section className="page-heading"><div><span className="eyebrow">INSPECTION REPOSITORY</span><h2>Inspections</h2><p>Create, retrieve, and continue field inspection records.</p></div><button className="button button--gold" onClick={() => setOpen(!open)}>{open ? 'Close form' : 'New inspection'}</button></section>{error && <p className="form-error">{error}</p>}
  {open && <section className="panel form-panel"><h3>New inspection</h3><form className="form-grid" onSubmit={create}><label>Product / commodity name<input required value={form.productName} onChange={e => setForm({...form, productName:e.target.value})}/></label><label>Generic name<input value={form.genericName} onChange={e => setForm({...form, genericName:e.target.value})}/></label><label>Brand name<input value={form.brandName} onChange={e => setForm({...form, brandName:e.target.value})}/></label><label>Inspection location<input value={form.location} onChange={e => setForm({...form, location:e.target.value})}/></label><label className="wide">Officer notes<textarea value={form.notes} onChange={e => setForm({...form, notes:e.target.value})}/></label><button className="button button--gold" disabled={saving}>{saving ? 'Creating…' : 'Create inspection'}</button></form></section>}
  <section className="panel form-panel"><div className="form-grid"><label>Search<input value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })} placeholder="Product, number, officer"/></label><label>Status<select value={filters.state} onChange={e => setFilters({ ...filters, state: e.target.value })}><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="PROCESSING">Processing</option><option value="PENDING_REVIEW">Pending review</option><option value="VERIFIED">Verified</option></select></label><label>From<input type="date" value={filters.from} onChange={e => setFilters({ ...filters, from: e.target.value })}/></label><label>To<input type="date" value={filters.to} onChange={e => setFilters({ ...filters, to: e.target.value })}/></label></div></section><section className="panel">{items.length ? <div className="data-table"><div className="row table-head"><span>Product / inspection</span><span>Officer</span><span>Date / findings</span><span>Status</span></div>{items.map(i => <Link className="row" to={`/inspections/${i.id}`} key={i.id}><strong>{i.product_name}<small>{i.inspection_number}</small></strong><span>{i.officer_name}</span><span>{new Date(i.created_at + 'Z').toLocaleDateString()}<small>{i.findings_count} findings</small></span><StatusBadge status={i.state}/></Link>)}</div> : <EmptyState title="No inspections found" detail="Adjust filters or create an inspection." />}</section></>;
}
