import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { request } from '../lib/api';
import { useAuth } from '../lib/auth';
import { StatusBadge } from '../components/StatusBadge';
import { EmptyState } from '../components/EmptyState';
import { EvidenceImage } from '../components/EvidenceImage';

export function InspectionDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { token } = useAuth(); const [inspection, setInspection] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => request(`/inspections/${id}`, { token }).then(x => setInspection(x.inspection)).catch(e => setError(e.message));
  useEffect(() => { load(); }, [id, token]);
  async function analyze() { setBusy(true); setMessage(''); try { const result = await request(`/inspections/${id}/analyze`, { token, method: 'POST' }); setInspection(result.inspection); setMessage(result.analysis.message); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function report() { setBusy(true); setMessage(''); try { const result = await request(`/inspections/${id}/report`, { token, method: 'POST' }); setMessage(`${result.report.report_number}: ${result.generation.message}`); load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function removeInspection() { if (!window.confirm(`Delete ${inspection.inspection_number}? This permanently removes its evidence, declarations, findings, and reports.`)) return; setBusy(true); setError(''); try { await request(`/inspections/${id}`, { token, method: 'DELETE' }); navigate('/inspections', { replace: true }); } catch (e) { setError(e.message); setBusy(false); } }
  async function review(findingId, officerDecision) { setBusy(true); try { await request(`/findings/${findingId}/review`, { token, method: 'PATCH', body: { officerDecision } }); load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  if (error && !inspection) return <><Link className="back-link" to="/inspections">← Inspections</Link><p className="form-error">{error}</p></>;
  if (!inspection) return <p className="muted">Loading inspection…</p>;
  const aiDebug = (() => { try { return JSON.parse(inspection.ai_diagnostics_json || '{}'); } catch { return {}; } })();
  return <><Link className="back-link" to="/inspections">← Inspections</Link><section className="page-heading detail-heading"><div><span className="eyebrow">{inspection.inspection_number}</span><h2>{inspection.product_name}</h2><p>{inspection.generic_name || 'Generic commodity name not recorded'} · Officer: {inspection.officer_name}</p></div><StatusBadge status={inspection.state}/></section>{error && <p className="form-error">{error}</p>}{message && <p className="notice">{message}</p>}
  <div className="detail-grid"><section className="panel"><h3>Inspection record</h3><dl><dt>Brand</dt><dd>{inspection.brand_name || 'Not recorded'}</dd><dt>Location</dt><dd>{inspection.location || 'Not recorded'}</dd><dt>Created</dt><dd>{new Date(inspection.created_at + 'Z').toLocaleString()}</dd><dt>Notes</dt><dd>{inspection.notes || 'None'}</dd></dl></section><section className="panel"><h3>Actions</h3><p className="muted">Runs OCR-backed, deterministic preliminary checks. Final determination requires officer verification.</p><div className="action-stack"><button className="button button--gold" disabled={busy || !inspection.images.length} onClick={analyze}>{busy ? 'Working…' : 'Run preliminary analysis'}</button><button className="button button--secondary" disabled={busy} onClick={report}>Request report</button><button className="button button--danger" disabled={busy} onClick={removeInspection}>Delete inspection</button></div></section></div>
  <section className="panel"><div className="section-title"><div><h3>Evidence images</h3><p>Original files retained privately; OCR quality is shown per image.</p></div><span>{inspection.images.length} attached</span></div>{inspection.images.length ? <div className="image-list">{inspection.images.map(image => <EvidenceImage key={image.id} inspectionId={inspection.id} image={image} token={token} />)}</div> : <EmptyState title="No images uploaded" detail="Use the mobile field workflow to capture or select package-label images." />}</section>
  <section className="panel"><div className="section-title"><div><h3>OCR debug</h3><p>Development diagnostics for stored evidence and OCR output.</p></div></div>{inspection.images.map(image => <div className="declaration" key={`ocr-${image.id}`}><strong>{image.image_type} — OCR {image.ocr_status || 'NOT_RUN'}</strong><small>Confidence: {image.ocr_confidence == null ? 'Not available' : `${Math.round(image.ocr_confidence * 100)}%`}</small>{image.ocr_error && <small>OCR error: {image.ocr_error}</small>}<strong>Raw OCR</strong><pre>{image.ocr_text || 'No OCR text stored for this image.'}</pre><strong>Normalized OCR</strong><pre>{image.normalized_ocr_text || 'No normalized OCR text stored for this image.'}</pre></div>)}</section>
  <section className="panel"><div className="section-title"><div><h3>AI extraction debug</h3><p>Development diagnostics; AI only structures OCR candidates and never makes legal conclusions.</p></div></div><dl><dt>AI service invoked</dt><dd>{aiDebug.invoked ? 'Yes' : 'No'}</dd><dt>Provider / model</dt><dd>{aiDebug.provider || 'Unavailable'} / {aiDebug.model || '—'}</dd><dt>Input OCR character count</dt><dd>{aiDebug.inputOcrCharacterCount ?? 0}</dd><dt>Extraction success</dt><dd>{aiDebug.success ? 'Yes' : 'No'}</dd><dt>Fallback used</dt><dd>{aiDebug.fallbackUsed ? 'Yes' : 'No'}</dd>{aiDebug.error && <><dt>Diagnostic</dt><dd>{aiDebug.error}</dd></>}</dl><pre>{JSON.stringify(aiDebug.output || [], null, 2)}</pre></section>
  <section className="panel"><div className="section-title"><div><h3>Extracted declarations</h3><p>OCR plus deterministic parsing. Missing fields remain not detected.</p></div></div>{inspection.declarations.length ? <div className="data-table"><div className="row table-head"><span>Field</span><span>Value / OCR evidence</span><span>Confidence</span><span>State</span></div>{inspection.declarations.map(d => <div className="row" key={d.id}><span>{d.field_name.replaceAll('_', ' ')}</span><strong>{d.value || 'Not detected'}<small>{d.ocr_evidence || 'No OCR evidence'} · Source: {inspection.images.find(image => image.id === d.source_image_id)?.image_type || '—'} · {d.extraction_source || 'DETERMINISTIC'}</small></strong><span>{Math.round((d.confidence || 0) * 100)}%</span><span>{d.extraction_state || d.detection_state}</span></div>)}</div> : <EmptyState title="No declarations extracted" detail="Run preliminary analysis after adding acceptable evidence images." />}</section>
  <section className="panel"><div className="section-title"><div><h3>Automated findings</h3><p>AI-assisted preliminary assessment. Final determination is subject to verification by an authorized enforcement officer.</p></div></div>{inspection.findings.length ? <div className="data-table">{inspection.findings.map(f => <div className="row" key={f.id}><StatusBadge status={f.status}/><span>{f.message}<small>{f.rule_code} · {f.legal_reference}</small></span><span>{f.officer_decision || 'Unreviewed'}</span>{!f.officer_decision && <span><button className="text-button" disabled={busy} onClick={() => review(f.id, 'CONFIRMED')}>Confirm finding</button><button className="text-button" disabled={busy} onClick={() => review(f.id, 'REJECTED')}>Reject finding</button></span>}</div>)}</div> : <EmptyState title="No automated findings" detail="Run preliminary analysis after acceptable evidence images are available." />}</section></>;
}
