import { useState } from 'react';
import { Navigate } from 'react-router-dom';
import { request } from '../lib/api';
import { useAuth } from '../lib/auth';
import { useTheme } from '../lib/theme';

const blankRegistration = { fullName: '', email: '', phone: '', employeeId: '', department: '', designation: '', password: '', confirmPassword: '' };
export function LoginPage() {
  const { token, login } = useAuth(); const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [form, setForm] = useState(blankRegistration); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false);
  const { isDark } = useTheme();
  if (token) return <Navigate to="/" replace />;
  const update = (field, value) => setForm(current => ({ ...current, [field]: value }));
  async function submitLogin(event) { event.preventDefault(); setError(''); setLoading(true); try { login(await request('/auth/login', { method: 'POST', body: { email, password, application: 'WEB' } })); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  async function submitRegistration(event) { event.preventDefault(); setError(''); setNotice(''); setLoading(true); try { const result = await request('/auth/register/admin', { method: 'POST', body: form }); setForm(blankRegistration); setMode('login'); setNotice(result.registration.message); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <div className="login-page"><section className="login-panel login-panel--wide"><img className="login-mark" src={isDark ? '/legalmetrix-mark-dark.svg' : '/legalmetrix-mark-light.svg'} alt="LegalMetrix logo mark"/><span className="eyebrow">{mode === 'login' ? 'ADMINISTRATIVE COMMAND CENTRE' : 'ADMINISTRATOR REGISTRATION'}</span><h1>{mode === 'login' ? 'LegalMetrix' : 'Register as Admin'}</h1><p>{mode === 'login' ? 'Secure preliminary compliance assessment for authorized administrators.' : 'Your registration will remain Pending Verification until an approved administrator reviews it.'}</p>{notice && <p className="notice">{notice}</p>}{mode === 'login' ? <form onSubmit={submitLogin}><label>Official email<input type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required /></label>{error && <p className="form-error">{error}</p>}<button className="button button--gold" disabled={loading}>{loading ? 'Signing in…' : 'Sign in to Command Centre'}</button></form> : <form className="auth-registration" onSubmit={submitRegistration}><label>Full name<input value={form.fullName} onChange={e => update('fullName', e.target.value)} required /></label><label>Official email<input type="email" value={form.email} onChange={e => update('email', e.target.value)} autoComplete="email" required /></label><label>Phone number<input value={form.phone} onChange={e => update('phone', e.target.value)} inputMode="tel" required /></label><label>Employee / Admin ID<input value={form.employeeId} onChange={e => update('employeeId', e.target.value)} required /></label><label>Department / Office<input value={form.department} onChange={e => update('department', e.target.value)} required /></label><label>Designation<input value={form.designation} onChange={e => update('designation', e.target.value)} required /></label><label>Password<input type="password" value={form.password} onChange={e => update('password', e.target.value)} autoComplete="new-password" minLength="8" required /></label><label>Confirm password<input type="password" value={form.confirmPassword} onChange={e => update('confirmPassword', e.target.value)} autoComplete="new-password" minLength="8" required /></label>{error && <p className="form-error auth-wide">{error}</p>}<button className="button button--gold auth-wide" disabled={loading}>{loading ? 'Submitting…' : 'Submit administrator registration'}</button></form>}<button className="auth-switch" onClick={() => { setError(''); setNotice(''); setMode(current => current === 'login' ? 'register' : 'login'); }}>{mode === 'login' ? 'Register as Admin' : 'Return to administrator sign in'}</button><small>Authorized administrative access only. Field Officers must use the LegalMetrix mobile application.</small></section></div>;
}
