import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { API_URL, request } from '../lib/api';
import { useAuth } from '../lib/auth';
import { StatusBadge } from '../components/StatusBadge';
import { EmptyState } from '../components/EmptyState';
import { ActionDialog } from '../components/ActionDialog';

export function ReportsPage() {
  const { token } = useAuth(); const [reports, setReports] = useState([]); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(null); const [pendingDelete, setPendingDelete] = useState(null);
  useEffect(() => { request('/reports', { token }).then(x => setReports(x.reports)).catch(e => setError(e.message)); }, [token]);
  async function reportBlob(report, download = false) { const viewer = download ? null : window.open('', '_blank'); if (viewer) viewer.opener = null; try { const response = await fetch(`${API_URL}/reports/${report.id}/file${download ? '?download=1' : ''}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Report file is unavailable.'); const url = URL.createObjectURL(await response.blob()); if (download) { const link = document.createElement('a'); link.href = url; link.download = `${report.report_number}.pdf`; link.click(); } else if (viewer) viewer.location.href = url; else throw new Error('Allow pop-ups to view the report, or use Download.'); setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (e) { if (viewer) viewer.close(); setError(e.message); } }
  async function removeReport() { const report = pendingDelete; if (!report) return; setDeleting(report.id); setError(''); try { await request(`/reports/${report.id}`, { token, method: 'DELETE' }); setReports(current => current.filter(item => item.id !== report.id)); setPendingDelete(null); } catch (e) { setError(e.message); } finally { setDeleting(null); } }
  return <><section className="page-heading"><div><span className="eyebrow">REPORT REPOSITORY</span><h2>Reports</h2><p>Report requests and generation status from inspection records.</p></div></section>{error && <p className="form-error">{error}</p>}<section className="panel">{reports.length ? <div className="data-table"><div className="row table-head"><span>Report</span><span>Inspection / Product</span><span>Status</span><span>Actions</span></div>{reports.map(r => <div className="row" key={r.id}><span>{r.report_number}</span><strong>{r.inspection_number}<small>{r.product_name}</small></strong><StatusBadge status={r.status}/><span><button className="text-button" onClick={() => reportBlob(r)}>View PDF</button><button className="text-button" onClick={() => reportBlob(r, true)}>Download</button><Link className="text-button" to={`/inspections/${r.inspection_id}`}>Inspection</Link><button className="text-button text-button--danger" disabled={deleting === r.id} onClick={() => setPendingDelete(r)}>{deleting === r.id ? 'Deleting…' : 'Delete report'}</button></span></div>)}</div> : <EmptyState title="No generated reports" detail="Generated reports will appear here when a report file is available." />}</section><ActionDialog open={Boolean(pendingDelete)} title="Delete report?" description={pendingDelete ? `Delete ${pendingDelete.report_number}? The stored PDF will be permanently removed.` : ''} confirmLabel="Delete report" variant="danger" loading={Boolean(deleting)} onCancel={() => setPendingDelete(null)} onConfirm={removeReport}/></>;
}
