const INSPECTION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PROCESSING: 'PROCESSING',
  PENDING_REVIEW: 'PENDING_REVIEW',
  OFFICER_REVIEW_COMPLETED: 'OFFICER_REVIEW_COMPLETED',
  VERIFIED: 'VERIFIED',
  POTENTIAL_NON_COMPLIANCE_CONFIRMED: 'POTENTIAL_NON_COMPLIANCE_CONFIRMED',
  ESCALATED_FOR_ENFORCEMENT_REVIEW: 'ESCALATED_FOR_ENFORCEMENT_REVIEW'
});

const ADMIN_DECISIONS = Object.freeze([
  INSPECTION_STATUS.VERIFIED,
  INSPECTION_STATUS.POTENTIAL_NON_COMPLIANCE_CONFIRMED,
  INSPECTION_STATUS.ESCALATED_FOR_ENFORCEMENT_REVIEW
]);
const POTENTIAL_OUTCOME_DECISIONS = Object.freeze([
  INSPECTION_STATUS.POTENTIAL_NON_COMPLIANCE_CONFIRMED,
  INSPECTION_STATUS.ESCALATED_FOR_ENFORCEMENT_REVIEW
]);
const LEGACY_STATUS_MAP = Object.freeze({
  PRODUCT_REJECTED: INSPECTION_STATUS.ESCALATED_FOR_ENFORCEMENT_REVIEW,
  POTENTIAL_ISSUE: INSPECTION_STATUS.POTENTIAL_NON_COMPLIANCE_CONFIRMED
});

module.exports = { INSPECTION_STATUS, ADMIN_DECISIONS, POTENTIAL_OUTCOME_DECISIONS, LEGACY_STATUS_MAP };
